[project]
name = "feder-root"
version = "0.1.0"
description = "LAE flight data collection and access system"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "bump-my-version>=1.1.1",
    "hypothesis>=6.131.3",
    "pyright>=1.1.397",
    "pytest>=8.3.5",
    "python-lsp-server[all]>=1.12.2",
    "ruff>=0.11.2",
]

[tool.uv.workspace]
members = ["libs/*", "apps/*", "api"]
