[project]
name = "feder-scheduler"
version = "1.2.1"
description = "Feder Slurm scheduler"
readme = "README.md"
authors = [
    { name = "Ian Ross", email = "iross@mit.edu" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "click>=8.1.8",
    "feder-server",
]

[project.scripts]
feder-scheduler = "feder_scheduler:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
feder-server = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/feder_scheduler"]
