[project]
name = "feder-ingest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ian Ross", email = "iross@mit.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "feder-common",
    "feder-server",
    "psutil>=7.0.0",
]

[project.scripts]
feder-ingest = "feder.ingest:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
feder-common = { workspace = true }
feder-server = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/feder"]
