[project]
name = "feder-ingest"
version = "0.2.4"
description = "Feder ingester"
readme = "README.md"
authors = [
    { name = "Ian Ross", email = "iross@mit.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "feder-common",
    "feder-server",
    "lz4>=4.4.5",
    "prometheus-client>=0.21.1",
]

[project.scripts]
feder-ingest = "feder_ingest:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
feder-common = { workspace = true }
feder-server = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/feder_ingest"]
