[project]
name = "feder-rx"
version = "1.2.1"
description = "Feder receiver"
readme = "README.md"
authors = [
    { name = "Ian Ross", email = "iross@mit.edu" }
]
requires-python = ">=3.13,<3.14"
dependencies = [
    "click>=8.1.8",
    "feder-common",
    "feder-server",
    "pandas>=2.2.3",
    "prometheus-client>=0.21.1",
    "pyarrow>=19.0.1",
    "requests>=2.32.3",
]

[project.scripts]
feder-rx = "feder_rx:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
feder-common = { workspace = true }
feder-server = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/feder_rx"]
