# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: points.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'points.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpoints.proto\"M\n\x06Points\x12\x10\n\x04time\x18\x01 \x03(\x04\x42\x02\x10\x01\x12\x0f\n\x03lon\x18\x02 \x03(\x02\x42\x02\x10\x01\x12\x0f\n\x03lat\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x0f\n\x03\x61lt\x18\x04 \x03(\x05\x42\x02\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'points_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINTS'].fields_by_name['time']._loaded_options = None
  _globals['_POINTS'].fields_by_name['time']._serialized_options = b'\020\001'
  _globals['_POINTS'].fields_by_name['lon']._loaded_options = None
  _globals['_POINTS'].fields_by_name['lon']._serialized_options = b'\020\001'
  _globals['_POINTS'].fields_by_name['lat']._loaded_options = None
  _globals['_POINTS'].fields_by_name['lat']._serialized_options = b'\020\001'
  _globals['_POINTS'].fields_by_name['alt']._loaded_options = None
  _globals['_POINTS'].fields_by_name['alt']._serialized_options = b'\020\001'
  _globals['_POINTS']._serialized_start=16
  _globals['_POINTS']._serialized_end=93
# @@protoc_insertion_point(module_scope)
