import "feder/common/points.proto";

message Trajectory {
    required string source = 1;
    required string id = 2;
    required string transponder_id = 3;
    required string callsign = 4;
    optional string aircrafttype = 5;
    required Points points = 6;
}

message ReceiverHeartbeat {
    required string source = 1;
    required uint64 time = 2;
    required uint32 n_points_in_db = 3;
    required uint32 n_flights_in_db = 4;
    required uint64 last_point_in_db_time = 5;
    required uint64 n_trajectories_sent = 6;
}

message IngesterHeartbeat {
    required uint64 time = 1;
}

message Heartbeat {
   oneof heartbeat {
       ReceiverHeartbeat receiver = 1;
       IngesterHeartbeat ingester = 2;
   }
}
