[project]
name = "feder-common"
version = "1.2.1"
description = "Library for Feder shared between API and server processes"
readme = "README.md"
authors = [
    { name = "Ian Ross", email = "iross@mit.edu" }
]
requires-python = ">=3.12,<3.14"
dependencies = [
    "lz4>=4.4.5",
    "numpy>=1.24",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/feder_common"]
