# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feder/server/liveness.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'feder/server/liveness.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x66\x65\x64\x65r/server/liveness.proto\"\x1f\n\rLivenessQuery\x12\x0e\n\x06source\x18\x01 \x02(\t\"V\n\x10LivenessResponse\x12\x0e\n\x06source\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\x04\x12\x1f\n\x06status\x18\x03 \x02(\x0e\x32\x0f.LivenessStatus*K\n\x0eLivenessStatus\x12\x14\n\x10LIVENESS_UNKNOWN\x10\x00\x12\x0f\n\x0bLIVENESS_OK\x10\x01\x12\x12\n\x0eLIVENESS_ERROR\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feder.server.liveness_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIVENESSSTATUS']._serialized_start=152
  _globals['_LIVENESSSTATUS']._serialized_end=227
  _globals['_LIVENESSQUERY']._serialized_start=31
  _globals['_LIVENESSQUERY']._serialized_end=62
  _globals['_LIVENESSRESPONSE']._serialized_start=64
  _globals['_LIVENESSRESPONSE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
