# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feder/server/rabbitmq.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'feder/server/rabbitmq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from feder.common import points_pb2 as feder_dot_common_dot_points__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x66\x65\x64\x65r/server/rabbitmq.proto\x1a\x19\x66\x65\x64\x65r/common/points.proto\"\x81\x01\n\nTrajectory\x12\x0e\n\x06source\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\t\x12\x16\n\x0etransponder_id\x18\x03 \x02(\t\x12\x10\n\x08\x63\x61llsign\x18\x04 \x02(\t\x12\x14\n\x0c\x61ircrafttype\x18\x05 \x01(\t\x12\x17\n\x06points\x18\x06 \x02(\x0b\x32\x07.Points\"_\n\x11ReceiverHeartbeat\x12\x0e\n\x06source\x18\x01 \x02(\t\x12\x0c\n\x04time\x18\x02 \x02(\x04\x12\x15\n\rn_fixes_in_db\x18\x03 \x02(\r\x12\x15\n\rlast_fix_time\x18\x04 \x02(\x04\"!\n\x11IngesterHeartbeat\x12\x0c\n\x04time\x18\x01 \x02(\x04\"h\n\tHeartbeat\x12&\n\x08receiver\x18\x01 \x01(\x0b\x32\x12.ReceiverHeartbeatH\x00\x12&\n\x08ingester\x18\x02 \x01(\x0b\x32\x12.IngesterHeartbeatH\x00\x42\x0b\n\theartbeat')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feder.server.rabbitmq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAJECTORY']._serialized_start=59
  _globals['_TRAJECTORY']._serialized_end=188
  _globals['_RECEIVERHEARTBEAT']._serialized_start=190
  _globals['_RECEIVERHEARTBEAT']._serialized_end=285
  _globals['_INGESTERHEARTBEAT']._serialized_start=287
  _globals['_INGESTERHEARTBEAT']._serialized_end=320
  _globals['_HEARTBEAT']._serialized_start=322
  _globals['_HEARTBEAT']._serialized_end=426
# @@protoc_insertion_point(module_scope)
