CONTRAILS_API_SOURCE_NAME = 'contrails-api'
CSV_SOURCE_NAME = 'csv'
FLIGHTAWARE_SOURCE_NAME = 'flightaware'
OPENSKY_SOURCE_NAME = 'opensky'
OPENSKY_STATE_VECTOR_SOURCE_NAME = 'opensky-state-vectors'


SOURCE_NAMES = [
    CONTRAILS_API_SOURCE_NAME,
    CSV_SOURCE_NAME,
    FLIGHTAWARE_SOURCE_NAME,
    OPENSKY_SOURCE_NAME,
    OPENSKY_STATE_VECTOR_SOURCE_NAME
]
