#!/bin/bash

id=$(docker ps --filter name=rabbitmq --format '{{.ID}}' | head -n 1)

VIRTUAL_HOST=feder

docker exec $id rabbitmqctl add_vhost $VIRTUAL_HOST
docker exec $id rabbitmqctl add_user feder feder-test
docker exec $id rabbitmqctl set_permissions --vhost $VIRTUAL_HOST feder '.*' '.*' '.*'
docker exec $id rabbitmqctl set_user_tags --vhost $VIRTUAL_HOST feder administrator
